sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: jiumeng
    password: 1721jiumeng
  #alioss:
    #endpoint: oss-cn-beijing.aliyuncs.com
    #access-key-id: 
    #access-key-secret:
    #bucket-name:
  redis:
    host: localhost
    port: 6379
    database: 10

